quadrantChart
    title Reach and engagement of campaigns
    x-axis Low Reach --> High Reach
    y-axis Low Engagement --> High Engagement
    quadrant-1 We should expand
    quadrant-2 Need to promote
    quadrant-3 Re-evaluate
    quadrant-4 May be improved
    "Python Snake Game by Python Engineer": [0.3, 0.6]
    "Snake Python by Edureka": [0.45, 0.23]
    "Python Snake Game by CodeWithHarry": [0.57, 0.69]
    "Snake Game in Python by LikeGeeks": [0.78, 0.34]
    "Python Snake Game by Real Python": [0.40, 0.34]
    "Our Target Product": [0.6, 0.7]
